#!/bin/bash

# Find the real path of the source file.
NOTES_SOURCE="${BASH_SOURCE[0]}"
# resolve $SOURCE until the file is no longer a symlink.
while [ -h "$NOTES_SOURCE" ]; do
  TARGET="$(readlink "$NOTES_SOURCE")"
  if [[ $TARGET == /* ]]; then
    NOTES_SOURCE="$TARGET"
  else
    NOTES_DIR="$(dirname "$NOTES_SOURCE")"
    # in case $NOTES_SOURCE was a relative symlink.
    NOTES_SOURCE="$NOTES_DIR/$TARGET"
  fi
done

NOTES_SRC_DIR="$(cd -P "$(dirname "$NOTES_SOURCE")" > /dev/null 2>&1 && pwd)"
NOTES_ENTRY_DIR="${NOTES_SRC_DIR}/notes.d"

git-command() {
  pushd "${SRC_DIR}"
  (set -x ; git "$@")
  popd
}

print_help() {
  cat <<EOT
Usage: notes (command|filename)

Commands:
  help                  Prints this help message.
  list                  List all note files.
  open                  Opens generated PDF file of notes.
  edit                  Edits the most recently edited note.
  git [git-command], status, push, pull, commit
                        Runs specified git command on the notes directory.
  make [target]         Runs specified make target on the notes directory.
EOT
}

set -e
case "${1:-help}" in
  help)
    print_help
    ;;
  list)
    echo "${NOTES_ENTRY_DIR}"
    ls -1 "${NOTES_ENTRY_DIR}"
    ;;
  open)
    xdg-open "${SRC_DIR}/out/notes.pdf"
    ;;
  git)
    shift
    git-command "$@"
    ;;
  status)
    git-command "status"
    ;;
  push)
    git-command "push"
    ;;
  pull)
    git-command "pull"
    ;;
  commit)
    git-command "$@"
    ;;
  make)
    shift
    make --no-print-directory -C "${NOTES_SRC_DIR}" "${@:-all}" check-privacy
    ;;
  edit)
    EDIT_NOTE="true"
    shift
    ;&
  *)
    if [[ "${EDIT_NOTE:-false}" == "true" ]]; then
      # The most recently edited note file will be opened.
      NOTE_NAME=$(find "$NOTES_ENTRY_DIR" -type f -name "*.tex" \
        -printf "%T@ %Tc %p\n" | sort -n | tail -1 \
        | awk '{ print $NF }' | xargs basename)
    else
      TODAY="$(date +%Y-%m-%d)"
      if [[ -z "$1" ]]; then
        NOTE_NAME="${TODAY}.tex"
      else
        NOTE_NAME="$1.tex"
      fi
    fi

    "${EDITOR:-vim}" "${NOTES_ENTRY_DIR}/${NOTE_NAME}"
esac
